apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'maven-publish'

android {
    namespace 'com.stfalcon.imageviewer'
    compileSdkVersion 36

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 36
    }

    compileOptions {
        targetCompatibility = JavaVersion.VERSION_1_8
        sourceCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8.toString()
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
            withJavadocJar()
        }
    }
}

publishing {
    publications {
        release(MavenPublication) {
            groupId = 'com.github.stfalcon'
            artifactId = 'stfalcon-imageviewer'
            version = '1.0.1'

            pom {
                description = 'A customizable full-screen image viewer with shared image transition support, "pinch to zoom" and "swipe to dismiss" gestures.'
                name = 'StfalconImageViewer'
                url = 'https://github.com/stfalcon-studio/StfalconImageViewer'
            }

            afterEvaluate {
                from components.release
            }
        }
    }
}

dependencies {
    api 'androidx.appcompat:appcompat:1.1.0'
    api 'androidx.transition:transition:1.2.0'
    implementation 'com.github.chrisbanes:PhotoView:2.2.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

repositories {
    maven { url "https://jitpack.io" }
}

// Avoid Kotlin docs error
tasks.withType(Javadoc) {
    enabled = false
}

// Remove javadoc related tasks
task javadoc(type: Javadoc) {
    source = android.sourceSets.main.java.srcDirs
    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
}